# Generated by Django 5.2 on 2025-05-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_user_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
