# Generated by Django 5.2.1 on 2025-05-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_listing_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='image_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
