# Generated by Django 5.2.1 on 2025-05-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listingimage_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Commercial', 'Commercial'), ('Land', 'Land')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='room_count',
            field=models.IntegerField(default=1),
        ),
    ]
