# Generated by Django 5.2.1 on 2025-05-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_property_type_listing_room_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='availability',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('Coming Soon', 'Coming Soon')], default='Immediate', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Renovated', 'Renovated'), ('Pre-owned', 'Pre-owned')], default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='furnishing',
            field=models.CharField(choices=[('Unfurnished', 'Unfurnished'), ('Partially Furnished', 'Partially Furnished'), ('Fully Furnished', 'Fully Furnished')], default='Unfurnished', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Auction', 'Auction')], default='For Sale', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='features',
            field=models.ManyToManyField(blank=True, to='listings.feature'),
        ),
    ]
