# Generated by Django 5.2.1 on 2025-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_feature_listing_availability_listing_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='availability',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('Coming Soon', 'Coming Soon')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Renovated', 'Renovated'), ('Pre-owned', 'Pre-owned')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='furnishing',
            field=models.CharField(choices=[('Unfurnished', 'Unfurnished'), ('Partially Furnished', 'Partially Furnished'), ('Fully Furnished', 'Fully Furnished')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Auction', 'Auction')], default='', max_length=50),
        ),
    ]
