# Generated by Django 5.2.1 on 2025-05-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listing_availability_alter_listing_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='featured',
        ),
    ]
