# Generated by Django 5.2.1 on 2025-05-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_listing_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
