# Generated by Django 5.2.1 on 2025-06-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_listing_property_type_alter_listing_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='size',
            field=models.CharField(choices=[('-', '-'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Master', 'Master')], default='', max_length=50),
        ),
    ]
